version: "3.8"

services:
  zomboid:
    container_name: pz_server_docker
    build: .
    env_file:
      - .env
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "8766:8766/udp"
    volumes:
      - ./game_files:/home/steam/pz-dedicated  # game
      - ./server_data:/home/steam/Zomboid      # Save and Config
    deploy:
      resources:
        limits:
          memory: 5G  # Container
    restart: unless-stopped
    stop_grace_period: 1m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
