version: "3.8"

services:
  zomboid:
    container_name: pz_server_docker
    build:
      context: .
      args:
        - STEAMAPPBRANCH=${STEAMAPPBRANCH}

    env_file:
      - .env

    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "27015:27015/tcp"

    volumes:
      - ./data:/home/steam/Zomboid

    restart: unless-stopped
    stop_grace_period: 1m

    logging:
      options:
        max-size: "10m"
        max-file: "3"
